name: Destroy Infrastructure
on:
  workflow_dispatch: # This adds the manual "Run workflow" button

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      
      - uses: pulumi/actions@v4
        with:
          command: destroy   # This DELETES the resources
          stack-name: myworkshop/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # Must match your OIDC environment path exactly
          PULUMI_ES_ENV: Muskaan-org/aws-oidc/dev
